# Generated by Django 4.2.30 on 2026-04-20 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "registration",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Immatriculation"
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveIntegerField(verbose_name="Nombre total de sièges"),
                ),
                (
                    "economy_seats",
                    models.PositiveIntegerField(verbose_name="Sièges classe Économie"),
                ),
                (
                    "business_seats",
                    models.PositiveIntegerField(verbose_name="Sièges classe Affaires"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Aéronef",
                "verbose_name_plural": "Aéronefs",
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code IATA"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'aéroport"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                ("country", models.CharField(max_length=100, verbose_name="Pays")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aéroport",
                "verbose_name_plural": "Aéroports",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Numéro de vol"
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(verbose_name="Heure de départ"),
                ),
                ("arrival_time", models.DateTimeField(verbose_name="Heure d'arrivée")),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programmé"),
                            ("boarding", "Embarquement"),
                            ("in_flight", "En vol"),
                            ("arrived", "Arrivé"),
                            ("delayed", "Retardé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "base_price_economy",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix de base Économie (TND)",
                    ),
                ),
                (
                    "base_price_business",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix de base Affaires (TND)",
                    ),
                ),
                (
                    "available_seats_economy",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sièges économiques disponibles"
                    ),
                ),
                (
                    "available_seats_business",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sièges affaires disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="flights.aircraft",
                        verbose_name="Aéronef",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="flights.airport",
                        verbose_name="Aéroport d'arrivée",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="flights.airport",
                        verbose_name="Aéroport de départ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vol",
                "verbose_name_plural": "Vols",
                "ordering": ["departure_time"],
                "indexes": [
                    models.Index(
                        fields=["origin", "destination"],
                        name="flights_fli_origin__ff1479_idx",
                    ),
                    models.Index(
                        fields=["departure_time"], name="flights_fli_departu_5bc2af_idx"
                    ),
                    models.Index(
                        fields=["status"], name="flights_fli_status_e6e528_idx"
                    ),
                ],
            },
        ),
    ]
