# Generated by Django 4.2.30 on 2026-04-20 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Référence de réservation",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=20, verbose_name="Téléphone de contact"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                            ("completed", "Terminée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant total (TND)",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Demandes spéciales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (TND)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Carte de crédit"),
                            ("debit_card", "Carte de débit"),
                            ("bank_transfer", "Virement bancaire"),
                            ("cash", "Espèces"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID de transaction"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                        verbose_name="Réservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Monsieur"),
                            ("mme", "Madame"),
                            ("mll", "Mademoiselle"),
                            ("enf", "Enfant"),
                        ],
                        max_length=4,
                        verbose_name="Titre",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nationalité"),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de passeport"
                    ),
                ),
                (
                    "passport_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration du passeport"
                    ),
                ),
                (
                    "travel_class",
                    models.CharField(
                        choices=[("economy", "Économie"), ("business", "Affaires")],
                        default="economy",
                        max_length=10,
                        verbose_name="Classe de voyage",
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Numéro de siège"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix payé (TND)"
                    ),
                ),
                (
                    "special_assistance",
                    models.BooleanField(
                        default=False, verbose_name="Assistance spéciale requise"
                    ),
                ),
                (
                    "meal_preference",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Préférence alimentaire"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="bookings.booking",
                        verbose_name="Réservation",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passengers",
                        to="flights.flight",
                        verbose_name="Vol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passager",
                "verbose_name_plural": "Passagers",
            },
        ),
    ]
